# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be applied
resources:
  - secretstore.yaml
  - ../base

patches:
  - target:
      kind: ExternalSecret
      name: not-so-secret
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: fake
