apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "my-secret-name"
        value: "HELLO1"
        version: "v1"
      - key: "my-other-secret-name"
        value: "HELLO2"
        version: "v1"