apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: not-so-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: my-azure-kv
  target:
    name: not-so-secret
    creationPolicy: Owner
  data:
  - secretKey: my-secret-value
    remoteRef:
      key: my-secret-name
      version: v1
  - secretKey: my-other-secret-value
    remoteRef:
      key: my-other-secret-name
      version: v1