# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be applied
resources:
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingressroute.yaml
